server:
  port: 80
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/miaomaifang?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接池配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

